.github/workflows/go.yml
internal/verifier/attestation_test.go
pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go
tools/benchmark/generate/main.go

I also had to fix a go vet finding in our benchmark generation.

Trigger go vet, gofmt, and goimports during the actions workflow.

---

tools/ctl/ctl.go

This fixes a number of issues that were introduced in #34 and #35. Specifically:
* benchmarks weren't being read successfully (read into local `set` then thrown away)
* The "Triggering rebuilds" message was printed *after* rebuilds had finished.
* The output needed to be flushed so some results were missing.

Fix run-bench input and output handling

---

cmd/proxy/main.go
pkg/proxy/policy/policy.go
pkg/proxy/policy/policy_test.go
pkg/proxy/proxy/transparent.go
pkg/proxy/proxy/transparent_test.go

- Add policy package that provides a Policy struct describing a set of rules applied to each incoming request.
- Add flag to toggle policy modes to determine whether or not a given policy should be applied to an incoming request.

Implement Policy for network proxy

---

internal/verifier/attestation.go
internal/verifier/attestation_test.go

Trim sha256 prefix from GCB

---

cmd/proxy/main.go
pkg/proxy/policy/policy.go
pkg/proxy/policy/policy_test.go
pkg/proxy/proxy/transparent.go
pkg/proxy/proxy/transparent_test.go

- Expose a /policy endpoint to update the network policy.
- Add a flag to read json files that set the network policy on startup.

Implement policy update methods

---

pkg/rebuild/schema/schema.go
tools/benchmark/run.go
tools/ctl/ctl.go

This removes the need for schema.MakeHttpRequest

Use benchmark.Run for ctl run-one

---

tools/ctl/ctl.go

Change run-one to use stubs instead of benchmark.Run. This allows run-one to configure UseNetworkProxy and UseSyscallMonitor.

Add more options to run-one.

---

tools/ctl/rundex/rundex.go

The change looks bigger than it is, most of it is an indentation and for loop.

Filter local runs when loading rebuilds.

---

cmd/stabilize/main.go
pkg/archive/archive.go

Add stabilize binary

---

tools/registryscan/main.go

Basic algorithm for locating registry state for #110

Add cargo registryscan PoC

---

tools/registryscan/main.go

This updates the search to scan backwards in day increments first, then binary search within that day's commits. This performs far better than the previous method (~7s, 20 resolutions vs ~150s, ~3000 resolutions) and should scale better with registry growth.
If necessary, we could also add an even more coarse week-based scan to begin the search if we discover the lock file states differ too much from the publication dates.

Use binary search to locate cargo registry state

---

pkg/rebuild/npm/infer.go

- This fixes a detection bug with 5.4.*

Port version logic to use semver

---

tools/ctl/rundex/rundex.go

This appears to be a classifier from pretty far back in the codebase and no current code appears to correspond.

Remove obsolete verdict transform

---

pkg/rebuild/debian/infer.go

Construct the debian strategy in-place
Include DSC URL in inference failure error message

refactor(debian): inference incrementally constructs strategy

---

pkg/rebuild/debian/infer.go

This was already added for .orig.tar.gz but wasn't yet added for
.debian.tar.gz or native source packages.

fix: Match on more variations of debian source material

---

pkg/rebuild/rebuild/workflowstrategy.go
pkg/rebuild/rebuild/workflowstrategy_test.go
pkg/rebuild/schema/schema.go
pkg/rebuild/schema/schema_test.go

This new strategy is based off of the melange syntax (which itself inherits from GitHub Actions and others) and allows us to expose individual commands as opposed to our current monolithic strategies.

Add workflow strategy

---

tools/ctl/ctl.go

Also, update the flag docstrings to reflect that the values are
command-specific.

Change format flag to default empty

---

deployments/main.tf

Avoids https://github.com/hashicorp/terraform-provider-google/issues/17605.

Migrate the terraform config to use Artifact Registry

---

tools/ctl/ctl.go
tools/ctl/ide/ui.go

This makes it easy to debug rebuilds locally, then commit upstream the
manual strategy changes that were generated.

Add tui flag to configure build definition dir

---

pkg/rebuild/flow/flow.go
pkg/rebuild/flow/flow_test.go
pkg/rebuild/flow/tool.go
pkg/rebuild/rebuild/workflowstrategy.go
pkg/rebuild/rebuild/workflowstrategy_test.go
pkg/rebuild/schema/schema_test.go

- Tool definition is now plain data
- Tools can use templates in scripts and/or params
- Tools can invoke other tools

Create a core lib for workflows

---

pkg/rebuild/rebuild/workflowstrategy.go
tools/ctl/ide/ui.go

Convert strategies to workflow before editing

---

pkg/rebuild/cratesio/infer_test.go

Increases package coverage from 17% -> 48%

Add crates inference test

---

deployments/main.tf

Moves prebuild resources to terraform management for #273

Add prebuild binary upload resource

---

deployments/main.tf

Removed during merge conflict resolution in #300

Restore accidentally removed acl

---

pkg/archive/jar.go
pkg/archive/jar_test.go

Inspired by @algomaster99's great work triaging related java rebuild failures in https://github.com/algomaster99/reproducible-central/issues/21

Add JAR build metadata stabilizer

---

tools/ctl/ctl.go

This makes it easier to debug the core GCB invocation, without creating
unwanted artifacts like container images, attestations, or debug
objects.

Add the steps format on infer

---

pkg/rebuild/debian/infer.go
pkg/rebuild/debian/strategy.go
pkg/rebuild/debian/strategy_test.go
pkg/registry/debian/debian.go

This needs more work around deciding when to use the Debrebuild strategy type over the existing strategy.

Change debian inference to use Debrebuild

---

pkg/archive/jar.go
pkg/archive/jar_test.go

Continuation of https://github.com/msuozzo/oss-rebuild/pull/2 and https://github.com/msuozzo/oss-rebuild/pull/1
Related #324 #323

 feat: add stabilizer to preserve order of values

---

pkg/rebuild/rebuild/storage.go
tools/ctl/assetlocator/assetlocator.go
tools/ctl/ctl.go
tools/ctl/ide/ui.go
tools/ctl/localfiles/butler.go

Originally proposed in #366, most of the discussion happened over there.

Add the localfiles.Butler

---

internal/glob/glob.go
internal/glob/glob_test.go

Add a path matcher supporting ** wildcard

---

pkg/archive/custom.go
pkg/archive/custom_test.go

Support wildcards in custom stabilizer paths

---

pkg/archive/custom.go
pkg/archive/custom_test.go

Support multiple paths per stabilizer entry

---

internal/gitx/gitxtest/git.go
pkg/rebuild/cratesio/infer_test.go

This allows the test repo to be placed on the local OS fs.

Add repo storage options to gitxtest

---

internal/api/apiservice/rebuild.go
internal/api/apiservice/rebuild_test.go
internal/verifier/attestation.go
internal/verifier/attestation_test.go
pkg/builddef/set.go
pkg/builddef/set_test.go
pkg/rebuild/schema/schema.go

Add dedicated BuildDefinition type

---

tools/ctl/ctl.go

This is a prototype change - happy to take in feedback and address it!

Add shell-script as an output format in the infer tool

---

tools/ctl/ide/ui.go

This isn't perfect as the actual stabilize comparison may have been different
but, for now, this better reflects the comparison made during the rebuild.

Stabilize TUI diff inputs

---

internal/api/apiservice/rebuild_test.go
pkg/registry/debian/debian.go

When snapshot doesn't have a matching version, try again using an epoch
of 1:

Add a debian epoch of 1: on failures

---

internal/api/form/form_test.go
internal/api/rpc.go
pkg/archive/manifest.go
pkg/rebuild/cratesio/rebuild.go
pkg/rebuild/flow/flow.go

$ go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest ./...

Run modernize

---

tools/ctl/ide/ui.go

The diff command was not waiting for diffoscope to complete before
cleaning up the temp files. The new-window command completes once the
window is created, and does not wait for the launched process.
I made the tmuxWait helper to do the same pattern we do with build def
editing.

TUI wait for diffoscope before cleanup

---

tools/ctl/ide/ui.go
tools/ctl/rundex/rundex.go

There was a lot of firestore naming that's no longer accurate.

Cleanup rundex naming

---

tools/ctl/ide/explorer/explorer.go

This means we unconditionally stabilize artifacts, even if they're from a smoketest that already stabilized them.

Remove smoketest logic from diffoscope code

---

internal/verifier/attestation.go

When the strategy requires timewarp, the current workaround to extract the
Location during attestation creation will not work. A dummy URL is provided in
this change to at least get the instructions to render (but remain unused) so
the Location remains accessible.

Fix attestation of strategies that use timewarp

---

site/index.html

This was previously not under version control.

Track the website landing page

---

README.md

The light logo should go with the dark theme...

Fix the logo selection

---

tools/ctl/ctl.go
tools/ctl/ide/assistant/assistant.go
tools/ctl/ide/commands/commands.go
tools/ctl/ide/ui.go

So far, this only implements the summary and identification of common classes, but not the re-labeling of each error into those classes which I still need to add.
Furthermore, I'm not 100% convinced assistant has the right interface here. I don't think *llm.Chat is the correct object, but I'm not sure exactly what I need yet. TBD.

Add AI error clustering

---

docs/index.md

In the absence of a good nav component, providing top-level links out to the
rest of the docs can help us make the available content more discoverable.

Add more links within the docs

---

pkg/feed/tracker.go

This is the structure of data as it will be stored in GCS and
distributed broadly.

Add the TrackedPackageSet schema type

---

internal/gcb/gcb.go

This requires a workaround for the current GCB Operations ID scheme.

Use regional operation endpoint for private pool

---

tools/ctl/ide/explorer/explorer.go

Fetching the reference was broken

Fix history reference type to be nodeData

---

tools/registryscan/main.go

The binary search ended up creating inefficiencies as recreating the
commit iterator incurs overhead of sorting/iterating to the correct
point each time. As a consequence, reusing a single one is still faster
even though it checks more individual commits in the common case.

Use linear instead of binary search for lockfile

---

pkg/build/gcb/executor.go

* Executor.activeBuilds is used to keep track of which builds need to be
cleaned up on Close.
* handle.setResult is used to signal that Wait can safely return.
The existing logic allowed code like the following to reach Close with
the build still considered active and, thus, necessary to clean up:
handle.setResult()
handle.Wait()
executor.Close() // observes and tries to cancel the completed build from activeBuild
executor.activeBuilds.Delete()

Fix race condition in GCB execution

---

pkg/kmsdsse/kmsdsse.go

This should not change anything functional in the signature but rather
move the digest calculation from the API (i.e. server-side in Cloud KMS)
to our code (i.e. client-side).
Notably, there is an API constraint that content be <=64kB when using
server-side hashing so we can allow for larger attestation payloads by
moving that client-side.

Use client-side digest computation for signing

---

internal/api/rpc.go
internal/api/rpc_test.go

When we convert error objects into grpc status objects, then into http
codes, we lose the message. This means the receiver (usually a stub
caller) doesn't have any details of the failure besides the code.
For services like inference, this means a lot of rebuilds have a failure
explanatation (`message`) that looks something like:
```
getting strategy: fetching inference: 500 Internal Server Error: non-OK
response
```
When really, that failure message should include the error contents
generated by the inference service.
Note that we still preserve the correct status code in the response, so that information is not lost.

Include error messages in http errors

---

docs/index.md

#711 helped get from GH to site
this one does the same to go from docs to site

add same link as #711 in docs

---

pkg/build/gcb/executor.go

Add tags to gcb executor

---

tools/ctl/ide/commands/commands.go

This is helpful when you want to re-run a specific class of failures.
You start by clustering using either the hardcoded error message
matching, or via AI Clustering. This makes generating those benchmarks
easy.

Add generate benchmark tui command

---

pkg/build/gcb/executor.go
pkg/build/gcb/executor_test.go

This fixes a regression from #688. When using rebuildremote.go, we were
converting gcloud build objects into error codes here:
https://github.com/google/oss-rebuild/blob/41820dcc2f2c8c88a1351f111bc433251747aa13/pkg/rebuild/rebuild/rebuildremote.go#L522
But that behavior didn't make it over to the new gcb executor.
Without this PR, all build failures materialize as comparison failures
when the api attempts to read the non-existant rebuilt artifact.

Convert failed builds to errors

---

pkg/rebuild/maven/infer.go
pkg/rebuild/maven/infer_test.go
pkg/rebuild/maven/maveninfer.go
pkg/rebuild/maven/maveninfer_test.go
pkg/rebuild/maven/strategy.go
pkg/rebuild/maven/strategy_test.go

Split inference depending upon build tool

---

pkg/rebuild/maven/infer.go

The information about `groupID` is irrelevant here.

Improve docstring of `inferBuildTool`

---

pkg/rebuild/maven/gradleinfer.go
pkg/rebuild/maven/infer.go
pkg/rebuild/maven/infer_test.go
pkg/rebuild/maven/maveninfer.go

This new heuristic goes through the log history and compares `SHA256` hash of source files in upstream `-sources.jar` and the repository. We go through the log (ordered by time) and then compare hash of each file in a commit with the hash in sources jar. We select for the local maxima in the log; this is to avoid searching through the entire log history. For example, first commit returns 5 matching files; second commit 7; third commit 6. We return the second commit immediately. I have also added some test cases which reflect this behavior.
Todo:

Use source jar to approximate commit

---

internal/api/inferenceservice/infer.go

Fix condition for inference without repo hint

---

internal/llm/chat.go

#558 accidentally removed this and hasn't been caught since :(

Restore function calling to chat

---

pkg/rebuild/maven/gradleinfer.go
pkg/rebuild/maven/infer.go
pkg/rebuild/maven/strategy.go
pkg/rebuild/maven/strategy_test.go

@msuozzo are the changes good or would you want to incorporate checking if we need to install gradle during inference?

Add support for installing system-wide gradle

---

internal/api/cratesregistryservice/findcommit.go
pkg/registry/cratesio/index/find.go
pkg/registry/cratesio/index/find_test.go
tools/registryscan/main.go

There's not much benefit to the single-index form and we don't foresee
using it. Best to remove it and leave its reintroduction to a future
where we might need it.

Remove unused index search function
