.github/workflows/jekyll-gh-pages.yml

This is adds the default github-provided workflow to publish to pages. This is motivated by a lack of support for symlinks in the builtin pages deployment workflow. Per [the docs](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error):
> Note: If your repository contains symbolic links, you will need to publish your site using a GitHub Actions workflow. For more information about GitHub Actions, see "[GitHub Actions documentation](https://docs.github.com/en/actions)."

Use github actions to publish to pages

---

cmd/api/main.go
go.mod
pkg/kmsdsse/kmsdsse.go

Direct use of the genproto target is deprecated. This moves the proto dep to be managed by the cloud.google.com KMS lib.

Update KMS proto dependency

---

cmd/gateway/main.go

We already have one for crates and github, but not pypi. The most recent attestation run had some pypi rejections which this will hopefully fix.

Add a gateway limit for pypi.org

---

cmd/api/main.go
cmd/rebuilder/main.go
pkg/rebuild/schema/schema.go

The API smoketest endpoint now returns verdict objects. I also changed the schema.SmoketestVerdict to be just schema.Verdict

Add verdicts to API smoketest endpoint response

---

internal/httpegress/httpegress.go
tools/ctl/ctl.go

Change the run-bench to detecting a url that looks like a cloud run url (the same way run-one does). Based on this switch, run-bench will only conditionally upgrade to https or include an oauth token.
When the `--build-local` bool flag is provided, run-bench will skip the runid creation process, and it will also skip the warmup checks.
To help with running the local builder, the user agent is now optional.

Support run-bench targeting local instance of rebuilder.

---

tools/ctl/ctl.go

run-bench only collected the HTTP results but didn't have any visibility when a 200 happened. This PR adds much richer logging on run-bench to keep track of the verdicts being returned.
As part of this PR I refactored the run-bench goroutines into a first class struct called a WorkerPool, and the different types of runs (smoketest vs attest) are each an implementation of a PackageWorker.

Refactor run bench to print verdicts

---

internal/uri/uri.go
internal/uri/uri_test.go
pkg/rebuild/pypi/infer.go
pkg/registry/pypi/pypi.go

After we added support for unknown repos, this heuristic needed some
love. I changed to a prioritized system with the following order:
1. Homepage if it's using a uri pointing to a common repo host.
1. Project links using a common "source" name, with common uri host.
1. Project links using a common "source" name, with uncommon uri host.
1. Description links using a common host uri.
1. Project links outside the common "source" name, with common uri host.

 Refactor python repo inference.

---

cmd/api/main.go
cmd/inference/main.go
cmd/rebuilder/main.go
pkg/rebuild/schema/form/form.go
pkg/rebuild/schema/form/form_test.go
pkg/rebuild/schema/schema.go
tools/ctl/ctl.go

While the use of reflection is sub-optimal, we can end up removing a great deal of the boilerplate in our handlers and unblock the use of the upcoming rpc library.

Create a serialization lib for url.Values

---

internal/api/rpc.go
internal/api/rpc_test.go

The major benefit of this small bit of code is we can separate the complex dependencies and binary-configured settings from the handler implementations which (finally) makes them feasible to test. To boot, we also get type safety for cross-service RPCs and encoding/decoding boilerplate for free.

Create a simple RPC framework

---

cmd/api/main.go
internal/api/apiservice/rebuild.go

Add firestore logging for attestation based executions.
I split the RebuildPackage function into a handful of smaller functions. The motivation is that I wanted to capture most failure types that do an early return with an error. By pushing the "meat" of execution into these new functions, there's only one or two return values I need to capture and write to firestore, rather than lots of early return errors.

Firestore logging for RebuildRemote

---

internal/firestoretest/emulator.go

No current plans about how/whether to hook this into our existing testing since it requires a `gcloud` installation with the firestore emulator component. For now, we can use it for local testing/experimentation with firestore.

Add test library for firestore emulator.

---

tools/ctl/ctl.go

Without this the TUI was failing to actually run-bench due to an argument skew.

Use the CreateRun schema types.

---

tools/ctl/ctl.go
tools/ctl/firestore/firestore.go
tools/ctl/ide/ui.go

This caused debugging to be really challenging, TUI would simply crash and no useful error would be logged because output was still being redirected to the TUI component.
I think it's reasonable for the TUI to keep running even if a firestore query fails.
I also added a success log message because otherwise empty queries are indistinguishable from hung queries.

Firestore should return error gracefully.

---

cmd/api/main.go
deployments/main.tf
internal/api/apiservice/rebuild.go
internal/api/apiservice/rebuild_test.go
pkg/rebuild/rebuild/rebuildremote.go

Previously the metadata bucket was used for both the rebuilt artifacts and also the build info/docker file.
This gave cloud build unnecessary access to both the build info and the dockerfile which are both written and read by the orchestrator.
After this PR, cloud build only has Create access to the newly created rebuild-artifacts bucket. That bucket only stores:
1. The rebuilt artifact.
2. The docker image used for the build.
Further, cloud build no longer has access to the metadata bucket, which contains the build info and docker file. Because it's only used locally to the orchestrator, I considered switching it to a filesystem or in-memory asset store, except we want these assets available for debugging so I'm keeping it as a bucket for now.
One interesting affect of this PR, is that …

Split metadata bucket.

---

cmd/oss-rebuild/main.go

When fetching the build or steps from our attestations the CLI was converting them back to base64 instead of adding intendation. I think this is because we were asking the json encoder to Encode() a bytes string that was already json, so it encoded those bytes into base64 and added quotes outside it.

Json decode before encode in the CLI.

---

internal/textwrap/textwrap.go
internal/textwrap/textwrap_test.go

this mirrors python's textwrap.dedent to make string literals a bit easier to read in our go source files.

Add dedent utility

---

pkg/rebuild/npm/strategy.go
pkg/rebuild/npm/strategy_test.go

Comparing the two npm versions, `--` wasn't present in v7 while `-c` remains supported:
- v8: https://docs.npmjs.com/cli/v8/commands/npx
- v7: https://docs.npmjs.com/cli/v7/commands/npx
This manifested as failures during dependency install:
```
Error: Invalid tag name "cd . && npm install --force": Tags may not have any characters that encodeURIComponent encodes.
```

Use npx -c to ensure compatibility before npm@8.0.0

---

cmd/api/main.go
cmd/oss-rebuild/main.go
internal/api/apiservice/rebuild.go
internal/api/apiservice/rebuild_test.go
internal/verifier/attestation.go
internal/verifier/attestation_test.go
internal/verifier/attestor.go
internal/verifier/summary.go
internal/verifier/summary_test.go
pkg/builddef/set.go
pkg/rebuild/cratesio/rebuild.go
pkg/rebuild/cratesio/rebuild_test.go
pkg/rebuild/npm/rebuild_test.go
pkg/rebuild/pypi/rebuild_test.go
pkg/rebuild/rebuild/compare.go
pkg/rebuild/rebuild/rebuildmany.go
pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/storage.go
tools/ctl/ide/ui.go

Previously, The reader and writer apis had an ad hoc additional return value which was the ill-defined "resource path" for that asset. This change breaks that out into a more formal API and uses URLs as the medium of exchange.
As for the design choice to split out the URL() method into a separate interface: I found it useful to have users of this function declare in their signatures exactly where they want to "break out" of accessing assets exclusively through the AssetStore.

Separate out AssetStore path API

---

cmd/proxy/main.go
pkg/proxy/proxy/transparent.go

- Create constructor with mutex as a private member.
- Initialize the network log inside the constructor.
Closes #89

Add TransparentProxyService constructor

---

pkg/proxy/docker/docker.go
pkg/proxy/docker/docker_test.go
pkg/rebuild/cratesio/infer.go
pkg/rebuild/pypi/infer.go
pkg/rebuild/rebuild/rebuildone.go

The os errors are intended for use in OS I/O operations, not as generic errors for fs-like abstractions. See guidance: https://pkg.go.dev/os#IsNotExist

Migrate uses of os errors to fs equivalents

---

cmd/proxy/main.go
pkg/proxy/proxy/transparent.go
pkg/proxy/proxy/transparent_test.go

Add TransparentProxyServiceOpts struct to disable network activity logging in order to avoid unbounded memory usage.

Add option to disable capturing network activity log

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

Somehow, the gsutil builder image is currently ~2GB, granted some of that is
likely shared with the still-in-use docker builder (~800MB) so we won't see that
level of savings. Still, given we're only downloading public resources with gsutil,
the GCS HTTP API should be a more than sufficient replacement for our use-case.
For a cost estimate, pulling this build step is observed to take ~15s in a recent run
without the network proxy and, (unfortunately) >30s with the proxy.

Remove gsutil builder from rebuilds

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

While it will increase the size of the attestations and modestly lengthen the
build definitions themselves, this change means the image URI that ends up the
attestation itself will be a lot less ambiguous than just "alpine." This also
has the benefit of, if however slightly, weakening our (already substantial)
dependence on Docker-specific behavior.

Fully specify docker.io URIs

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

Both of these API pattern seems to be present in GCS's XML API for
compatibility with AWS S3. However the bucket-in-domain pattern is far more
reliable to parse than the other form as it overlaps with the standard GCS JSON
API path pattern (`/storage/...`).

Use virtual-hosted GCS URL

---

pkg/proxy/policy/policy.go
pkg/proxy/policy/policy_test.go
pkg/proxy/proxy/transparent_test.go

Add the ability to specify suffix or full string matching for host names in the proxy.

Add host matching to URLMatchRule

---

.github/workflows/go.yml
go.mod

With 1.23 released, 1.21 has gone out of the support window.

Bump go version to 1.22

---

docs/builds/ArtifactEquivalence@v0.1.md
docs/builds/Rebuild@v0.1.md
internal/api/apiservice/rebuild.go
internal/verifier/attestation.go
internal/verifier/attestation_test.go
internal/verifier/summary.go
internal/verifier/summary_test.go
pkg/archive/archive.go
pkg/archive/tar.go
pkg/archive/tar_test.go
pkg/archive/zip.go
pkg/archive/zip_test.go
pkg/rebuild/rebuild/compare.go
pkg/rebuild/rebuild/rebuildone.go

Since we're in the process of separating out the individual operations we're applying to artifacts, there won't be a single 'canonical' form for the artifact. The set of operations necessary to achieve a match between the rebuild and upstream artifacts may not match that of another rebuild-upstream pair. As such, our terminology should be flexible enough to encompass a spectrum of outcomes and, with this constraint, 'canonical' is no longer fit for purpose.
'normalized' was a close second but 'stabilized' is more permissive of this multiple endpoint usage. This term still appears in the ArtifactEquivalence attestation but will be migrated later in #135.

Rebrand 'canonical' to 'stable' for artifacts

---

internal/verifier/attestation.go
pkg/archive/archive.go
pkg/archive/common.go
pkg/archive/tar.go
pkg/archive/tar_test.go
pkg/archive/zip.go
pkg/archive/zip_test.go

Working towards a solution for #39

Separate out stabilization into configurable passes

---

pkg/rebuild/rebuild/rebuildmany.go
pkg/rebuild/rebuild/rebuildone.go

Not a major change but one consequence of this is that the Strategy and Timings will now be stored in the db entry for this run. That should give us more context to resume/edit/debug runs on failure.

Incrementally construct RebuildOne verdict

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

This improves docker layer caching for locally-executed builds with large deps.

Break up dependencies and source steps.

---

cmd/api/main.go
cmd/rebuilder/main.go
deployments/main.tf
internal/api/apiservice/rebuild.go
internal/api/apiservice/rebuild_test.go
pkg/rebuild/rebuild/rebuildremote.go

The uploads were not easy to access before, because they were behind the oblivious uuid. This change makes the rebuildremote debug handling more similar to the smoketest handling.
I don't love the increasing number of asset stores this PR adds, but it seemed necessary in order to store the BuildInfo in a location we can programatically find using the RunID.
I left a few comments suggesting we can combine the debug storage and the local store. My thinking is that we can combine them in a layered asset store that has an internal memfs cache. (draft #191) I'm not wedded to that idea, but it's an option to avoid the bloat of asset stores.

fix: Move rebuildremote uploads to the debug store

---

cmd/api/main.go
internal/api/rebuilderservice/smoketest.go
pkg/rebuild/rebuild/context.go
pkg/rebuild/rebuild/storage.go
tools/ctl/ctl.go

As far as I can tell, we weren't using DebugStoreID at all but it more accurately describes the value read in DebugStoreFromContext.
Optionally, we could rename this as DebugStorePathID.

refactor: Use DebugStoreID instead of ArtifactUploadID

---

pkg/rebuild/rebuild/rebuildremote.go

This is probably related to #122 and goes beyond what #129 accomplished.
In #129 we made sure dockerfile and build info are uploaded even when rebuild comparison or attestation fails. In this PR we upload whatever buildinfo is available even if GCB returned with an error.

fix: Always write the BuildInfo, even on failures

---

internal/gcb/gcb.go
pkg/rebuild/rebuild/rebuildremote.go

Before, the GCB code wouldn't return the build object on failures,
making it hard to log the BuildInfo in those cases. Now even GCB
build failures will update the BuildInfo and consequently logged,
which makes it easier to debug.

fix: Update BuildInfo before checking build status

---

tools/ctl/rundex/rundex.go

This is to support historical firestore entries that didn't include the
runid inside the document itself.

fix: Populate RunID using firestore document name

---

pkg/proxy/policy/policy.go
pkg/proxy/policy/policy_test.go

This is to avoid matching unintended domains. E.g. notgoogle.com must not match google.com, but is.google.com must.

perform domain suffix matching rather than plain string suffix one

---

pkg/rebuild/rebuild/rebuildremote.go

Only report errors about nil build results if the build was otherwise
error-free. This is because the build error is probably more descriptive
than build results, but we still want to emit an error when the results
are missing to avoid attesting without build image info.

fix: Check for nil build results

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go
tools/ctl/ctl.go

This adds the `--format=dockerfile` option on the `infer` command. It's helpful to see the full dockerfile when debugging inference, and easy to pipe this directly into docker locally. For example:
```
go run tools/ctl/ctl.go infer --ecosystem=debian --package=main/file --version=5.45-3+b1 --artifact=libmagic-mgc_5.45-3+b1_amd64.deb --format=dockerfile | docker buildx build -t tmp - && docker run -it -t tmp
```

Add dockerfile format to infer command

---

internal/api/rpc.go

This gives us guaranteed request logging for any services that are using
the api.Handler interface.

Add request logging to api.Handler function

---

internal/api/apiservice/rebuild.go

As is, the target is copied into the verdict before populating the
artifact, preventing the artifact making it back to the main handler.
This is problematic because the main handler uses the
artifact name as part of the firestore resource idenifier.

Write populated artifact into verdict

---

.gitignore
README.md

As an alternative to https://github.com/google/oss-rebuild/pull/251
This adds a note about the GCP ADC requirements for fetching the KMS public signing key. It does not seem that  unauthenticated access is supported for public signing keys.

docs: Add note about GCP ADC requirement to README

---

pkg/rebuild/npm/strategy.go
pkg/rebuild/npm/strategy_test.go

This new form should be equivalent but has a few nice properties:
* uses the same version of npm for `npm pack` as for `npm run`
* uses a single top-level command, encapsulating the logic in the npx invocation

Move npm custom build commands into npx call

---

cmd/oss-rebuild/main.go
cmd/oss-rebuild/verify.go

Embeds a pubkey in the CLI binary which, unless explicitly requested, will be
used instead of fetching it from Cloud KMS.
Fixes #250 where a GCP ADC was unconditionally required in the environment for
CLI --verify to function. Now, no such required should exist by default.

Support offline verify in CLI

---

pkg/rebuild/rebuild/workflowstrategy.go
pkg/rebuild/rebuild/workflowstrategy_test.go

Ecosystem-specific tools are defined alongside rebuild strategies instead of
centrally as this npm tool was. An equivalent exists for npm so this tool is no
longer necessary.

Remove obsolete npm flow tool

---

internal/api/inferenceservice/infer.go
internal/api/rebuilderservice/smoketest.go
pkg/rebuild/maven/infer.go
pkg/rebuild/maven/pom.go
pkg/rebuild/maven/pom_test.go
pkg/rebuild/maven/rebuild.go
pkg/rebuild/maven/strategy.go
pkg/rebuild/rebuild/registry.go
pkg/rebuild/schema/schema.go
pkg/registry/maven/maven.go
tools/indexscan/main.go

Hi team, this is a work in progress so the description here and implementation/changeset will change as it gets closer to complete. For now I wanted to make sure I am on the right path.
It seems that the `maven` implementation in the code does not yet use the `Rebuilder` or `Registry` interfaces. To simplify the code this PR aims to port the maven code to implement these. This is starting with `Registry` as that is a dependency and far simpler.
This PR aims to keep the coding style, imports, and other important but non-functional elements the same.

chore: Refactor maven implementation to use Registry and Rebuilder interfaces

---

cmd/proxy/main.go
pkg/proxy/docker/docker.go
pkg/proxy/docker/docker_test.go

Currently the proxy is only able to patch environment variables into the docker container by providing a key and mapping it to the certificate truststore. Allow key-value pairs through a different flag to support custom environment variables.

Add interface for patching env vars in network proxy

---

internal/api/apiservice/rebuild.go
pkg/rebuild/schema/schema.go

When executing streaming-style rebuilds, we will use a fixed runID. In these cases, we will likely want to group rebuilds based on when they were started, rather than when they were completed.

Record rebuild start time

---

pkg/rebuild/schema/schema.go
tools/benchmark/run.go
tools/benchmark/run_test.go
tools/ctl/ctl.go
tools/ctl/ide/rebuilder.go
tools/ctl/ide/ui.go
tools/ctl/rundex/rundex.go

The type of execution is not directly tied to benchmarks. This change helps decouple the benchmark construct from code locations that switch between execution modes.

Add schema.ExecutionMode to generalize BenchmarkMode

---

internal/taskqueue/taskqueue.go
tools/benchmark/run.go
tools/benchmark/run_test.go

This makes the taskqueue Add() function similar to stubs. As used currently, we're *always* enqueuing a schema.Message type so this helps remove boilerplate.

Change internal taskqueue to accept a schema.Message

---

tools/pypi_rss/listener/listener.go
tools/pypi_rss/listener/listener_test.go
tools/pypi_rss/main.go

This makes testing easier and cleans up the interface by pushing some
initialization into a dedicated NewListener function.

Move the pypi listener into a dedicated library

---

cmd/api/main.go
deployments/main.tf
internal/api/apiservice/rebuild.go
internal/verifier/attestation.go
internal/verifier/attestation_test.go
pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

Fixes #273, #124
This ensures that future updates to our build tools won't break already-published Dockerfiles contained in attestations.

Use versioned prebuilds

---

deployments/main.tf

Given that these GCS references remain in the Dockerfiles published in
provenance, we should be careful not to accidentally modify or delete them.

Add delete protection on prebuilds

---

deployments/main.tf

The gsutil cp command supports -P to copy the posix mode of the source
filesystem, but we're reading the file from a pipe so that's not
available. Instead we can set the posix mode after it's uploaded.

Set posix mode on bootstrap-tools

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

The proxy logic prepended a tab character which resulted in docker ignoring the
syntax pragma.
With this fixed, we were actually using features from beyond syntax version 1.4
in the existing proxy implementation so we need to update to 1.10 where support
for secret env vars was added.

Fix Dockerfile syntax usage

---

cmd/api/main.go
deployments/main.tf
internal/api/apiservice/rebuild.go
pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

This became necessary due to the recent introduction of non-public bootstrap
tools. This use of auth is not intended to be the common mode of execution as
it makes the resulting Dockerfile require an injected credential and should
primarily be used for non-public and/or test environments.

Support authenticated access to bootstrap tools

---

pkg/rebuild/npm/strategy.go
pkg/rebuild/npm/strategy_test.go

One issue with the previous global timewarp config is that it makes isolated
overrides cumbersome or infeasible. We've run into issues trying to use npm
versions from after the package was published (certain npm releases were broken
under our configuration) and working around the global npm config can be
challenging, especially when different configs are needed in the same npx
command (i.e. -p package can't have timewarp while the -c command needs it).

Use env var for 'npm install' timewarp support

---

pkg/rebuild/debian/strategy.go
pkg/rebuild/debian/strategy_test.go

This mitigates what seems to be a race condition in mmdebstrap, where the chroot isn't completely setup by the time our customize-hook runs.

Patch debrebuild to add sleep

---

internal/httpx/httpxtest/mockclient.go

Previously, when the validator was omitted, URL validation will be silently
skipped. Having an explicit parameter should help avoid accidental omission.

Ensure URL Validation explicitly disabled

---

internal/api/apiservice/rebuild_test.go
internal/httpx/httpxtest/mockclient.go
internal/proxy/dockerfs/dockerfs_test.go
internal/timewarp/timewarp_test.go
internal/verifier/summary_test.go
pkg/rebuild/cratesio/infer_test.go
pkg/registry/cratesio/cratesio_test.go
pkg/registry/debian/debian_test.go
pkg/registry/npm/npm_test.go
pkg/registry/pypi/pypi_test.go

This abbreviates the setup necessary to use the httpxtest.MockClient while
still allowing for customization, when necessary.

Add httpxtest.NewURLValidator

---

internal/gitx/gitxtest/git.go

For programmatic construction, YAML is a poor target. For these cases, it will
be easier to pass in the commit config directly.

Allow struct-based repo init in gitxtest

---

pkg/archive/jar.go
pkg/archive/jar_test.go
pkg/archive/zip.go

Reference: https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/825
The files `git.json` and `git. properties` are generated by https://github.com/git-commit-id/git-commit-id-maven-plugin. We delete these files in the jar file to stabilize. We assume default configuration that the files are either called `git.json` or `git.properties`.

feat: delete files containing git properties

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

This isn't strictly necessary, but it's helpful when clicking through
active GCB executions in the UI to find what you're looking for.

Print the target at the start of gcb logs

---

internal/api/rpc.go
internal/api/rpc_test.go

The Handlers are all expecting the request in the params, I think this
was broken before.

Change Translate to populate URL params not body

---

tools/ctl/rundex/rundex.go

Introduced in #423, this un-breaks the rundex pipeline. Without this
change the rundex was returning emtpy results.

Fix rundex filter pipeline

---

internal/timewarp/timewarp.go

The registry has no path component so this is a no-op.

Remove obsolete PyPI path addition

---

internal/timewarp/timewarp.go
internal/timewarp/timewarp_test.go

In addition to being more self-documenting, this offers functional benefits as
the CPU/memory cost of proxying the (often large) npm package archives is now
no longer duplicated by the timewarp binary. This should free up local
resources, especially for large and/or multitenant builds.

Use path to detect un-warped requests and redirect

---

pkg/proxy/policy/policy.go
pkg/proxy/policy/policy_test.go

HasPrefix was used incorrectly in this function so suffixes that already have a . will have another . prepended to it. Newly added test fails before change and passes after change.

Fix Suffix matching in URLMatchRule.Allows

---

internal/llm/tool.go

The terminology clash between "function" and "tool" is an annoyance but
both are used in the exposed API surface of genai so this, at worst, maintains
consistency with the underlying library.

Add support for LLM function definitions

---

pkg/rebuild/cratesio/infer_test.go

`tag` wasn't defined before this yet the test was inadvertently passing. This change ensures the RefMap doesn't contain the intended entry so we fall through to the tag heuristic.

Ensure tag codepath is covered

---

pkg/rebuild/npm/infer.go
pkg/rebuild/npm/infer_test.go
pkg/rebuild/npm/strategy.go
pkg/rebuild/npm/strategy_test.go

npm dropped privilege when running scripts in npm v6 and prior. the [v7 update](https://github.com/npm/cli/blob/e1a2837809a76896523cdfcbce7537e46f71d67e/CHANGELOG.md#:~:text=configurations%20are%20no%20longer%20relevant) uses the underlying directory owner which, in our case, will be the same as the calling user.

Add unsafe-perm for npm v6 invocations

---

pkg/rebuild/npm/strategy.go
pkg/rebuild/npm/strategy_test.go

This process is applicable to interactive sessions but not for CI builds.

Avoid auditing installed npm packages

---

internal/api/apiservice/createrun.go
internal/api/apiservice/rebuild.go
internal/api/apiservice/smoketest.go
pkg/rebuild/schema/schema.go
tools/ctl/ide/explorer/explorer.go
tools/ctl/rundex/rundex.go

We were inconsistent with timezone and Unix vs UnixMilli previously, causing a lot of bad data in our metadata storage.
After doing some data migrations, firestore contains the data as native time.Time types now.
I also removed the rundex.Rebuild.Created field, because that's now directly handled in embed schema.Attempt

Use native time.Time types in firestore and rundex

---

tools/ctl/rundex/rundex.go

The embedded struct already has a Created field, so this should be essentially a no-op.

Remove unneeded Created field from rundex.Run

---

tools/ctl/ide/commands/commands.go
tools/ctl/ide/commands/registry.go
tools/ctl/ide/explorer/explorer.go
tools/ctl/ide/modal/modal.go
tools/ctl/ide/textinput/textinput.go
tools/ctl/ide/ui.go

As part of this PR I'm also adding the RebuildGroupCmd type which is similar to RebuildCmd, except it operates over multiple rundex.Rebuild objects.

Add regex search across logs in a verdict group

---

tools/ctl/ide/assistant/session.go

The truncation behavior is to take the last X bytes, so really the "...truncated..." message should go at the start not the end.

Move truncated message to beginning

---

tools/benchmark/run/local.go
tools/benchmark/run/run.go
tools/ctl/ctl.go
tools/ctl/ide/rebuilder/rebuilder.go

This allows for a work-in-progress local docker execution of the build. There
are a number of improvements we can make here but this offers a minimal set of
changes to support this use-case.

Add execution abstraction to run-bench

---

tools/ctl/ide/ui.go

Previous input capture was set to the root of the application to make
sure ctrl-C worked everywhere, but that's a special case. The other
global commands should not be captured during modals or typing
elsewhere.

Only set global commands on the window

---

tools/ctl/ctl.go

Previously, when llm-project was omitted, the use of Vertex AI would fail at
usage time. This is still an issue to be addressed but will only happen when
the project flag is also omitted. Hopefully, in this case, the user will be
less surprised when the API call fails.

Make llm-project an override

---

pkg/archive/common.go
pkg/archive/gzip.go
pkg/archive/tar.go
pkg/archive/zip.go

Fixes #425 
The changes mark `Stabilizer` as an interface. For each of its implementations,  I added a method `Stabilize` for example
```go
func (g GzipStabilizer) Stabilize(arg any) {
if g.Func != nil {
g.Func(arg.(*MutableGzipHeader))
}
}
```
Now instead of `Func`, `Stabilize` is invoked everywhere. We could also make `Func` and `Name` fields private but I let them be for now.

refactor: add `Stabilize(any)` method to interface

---

internal/verifier/attestation.go

The builder source identity is captured in the prebuild and service internal
parameters.

Remove obsolete comment

---

internal/api/apiservice/rebuild.go
pkg/rebuild/cratesio/rebuild.go
pkg/rebuild/debian/rebuild.go
pkg/rebuild/maven/pom_test.go
pkg/rebuild/maven/rebuild.go
pkg/rebuild/npm/rebuild.go
pkg/rebuild/pypi/rebuild.go
pkg/rebuild/rebuild/rebuild.go
pkg/registry/maven/maven.go

Also adds UpstreamURL method to facilitate porting off of do<Ecosystem>Rebuild
pattern in rebuild logic.

Move RebuildRemote into Rebuilder

---

pkg/rebuild/pypi/strategy.go
pkg/rebuild/pypi/strategy_test.go

This avoids < and > being interpreted as shell redirects
To support single quotes inside the requirement spec, I added bash escaping for those quotes.

Wrap python requirements with single quotes

---

deployments/main.tf
deployments/modules/container_binary_upload/main.tf
deployments/modules/container_build_push/main.tf
deployments/modules/container_build_push/outputs.tf

Changing the outputs makes sure that terraform will wait for the images
to be built before proceeding.

Fix terraform output dependency

---

.github/workflows/jekyll-gh-pages.yml

This prevents forks from attempting to deploy github pages changes.

Add repo conditionals to jekyll actions

---

pkg/rebuild/rebuild/rebuildremote.go
pkg/rebuild/rebuild/rebuildremote_test.go

Since exec took in a multi-line string delimited by single quotes, the
Dockerfile itself would need to be escaped to account for this. But applying an
additional level of escaping is error-prone and makes the build step definition
diverge from expectation. To ensure the close relation between the build and
the Dockerfile, we move the file creation to the top-level script which then
passes the Dockerfile contents into the build container.

Move proxy Dockerfile creation out of exec

---

pkg/build/baseimage.go
pkg/build/build.go
pkg/build/options.go
pkg/build/packagemanager.go
pkg/build/packagemanager_test.go
pkg/build/plan.go
pkg/build/url.go
pkg/build/url_test.go

The upshot is we can split and reuse methods of executing builds from the way
we compose the builds themselves. This should give us cleaner abstractions to
express our existing builds as well as allow for greater reuse in developing
future build types.

Create new build abstraction

---

internal/syncx/genericmap.go
internal/syncx/genericmap_test.go

The stdlib does not yet support generics here so this layer provides a shim
until that occurs. Also included are a best-effort Len implementation as well
as a type-safe compare variant (where the value type is comparable).

Add a generic wrapper for sync.Map

---

internal/bufiox/linebuffer.go
internal/bufiox/linebuffer_test.go
internal/bufiox/pipe.go
internal/bufiox/pipe_test.go

This construct gives us a number of nice properties in implementing the build output streaming. For one, the ring buffer allows us to bound the memory cost of logs streaming for each build. Second, the line-based buffering helps us ensure logs remain human-readable even when eviction is necessary (mid-line breaks don't happen). Additionally, the use of the pipe means that the build invoker need not call `OutputStream()` to drain the output if they don't need it. And if they are interested in observing some failure after the build completes, the buffer is in a state to provide the last portion of the build output (although we currently close and free the buffer on termination).

Create BufferedPipe abstraction for log streaming

---

cmd/stabilize/main.go

Before this patch, `stabilize /path/to/a/tar.gz` would fail:
```
panic: runtime error: comparing uncomparable type archive.TarArchiveStabilizer
goroutine 1 [running]:
slices.Equal[...](...)
slices/slices.go:25
main.eligiblePasses({0x7fffffffe1ae, 0x10})
github.com/google/oss-rebuild/cmd/stabilize/main.go:185 +0x2fb
main.run()
github.com/google/oss-rebuild/cmd/stabilize/main.go:212 +0x198
main.main()
github.com/google/oss-rebuild/cmd/stabilize/main.go:246 +0x13
```

stabilize: fix error when stabilizing tars

---

tools/ctl/ide/commandreg/registry.go
tools/ctl/ide/commands/commands.go
tools/ctl/ide/explorer/explorer.go
tools/ctl/ide/ui.go

This allows UI elements to iterate over a registry and display commands,
while the command implementations can reference those same UI elements
when building modal UI objects

Split command registry and implementation

---

tools/ctl/ide/explorer/explorer.go
tools/ctl/ide/rebuildhistory/rebuildhistory.go
tools/ctl/ide/rundextable/rundextable.go
tools/ctl/ide/rundextree/rundextree.go
tools/ctl/ide/ui.go

We update the registry in a handful of places, most of the time we want
all references to point to the same registry. If that changes in the
future we can make a Copy() method.

Change command registry to pointer

---

tools/ctl/ide/commands/commands.go
tools/ctl/rundex/rundex.go

Previously when filtering by a benchmark set, the FirestoreClient would
query all records global only filtering clientside. This created
enormous wait times that conintued to grow as we add more documents.

Change FirestoreClient to handle benchmark filters faster

---

tools/ctl/ctl.go
tools/ctl/localfiles/butler.go
tools/ctl/localfiles/localfiles.go

This allows callers to specialize what storage the Butler is using when
fetching assets.

Add an assetStoreFn option on NewButler

---

tools/ctl/ctl.go

This can be used for collaborating on rebuild datasets

Add tui flag for shared asset store

---

analyzer/network/analyzer/main.go
cmd/api/main.go
cmd/oss-rebuild/verify.go
pkg/kmsdsse/kmsdsse.go
pkg/kmsdsse/kmsdsse_test.go

Requiring the key object requires external users to have the
cloudkms.cryptoKeyVersion.get permission which is not part of the
cloudkms.verifier role we grant to all users.
Accepting the resource name alone means the interface only need fetch
the public key (cloudkms.cryptoKeyVersion.getPublicKey).

Use key resource name as signer-verifier param

---

tools/ctl/ctl.go

Currently, an empty project manifests as a crash during the Service
Usage test for vertex enablement. This check isn't necessary in this
case given there's no chance of configuring the API in the first place.

Support empty project in TUI

---

pkg/rebuild/schema/schema.go

The change adds the missing strategy.

fix: add missing case for Maven rebuild strategy

---

pkg/rebuild/maven/infer.go
pkg/rebuild/maven/infer_test.go
pkg/rebuild/maven/pom.go
pkg/rebuild/maven/pom_test.go

Fixes #700 
I prioritize looking for `scm.url` in the `pom` or `parent pom` as that URL points to the source repository. `url`, by convention, is the project home page. For OSS-Rebuild, `url` is https://oss-rebuild.dev/ and not `https://github.com/google/oss-rebuild`.
We also need to resolve the parent pom for to scan for `scm.url` from there.

Resolve source repository URL from parent

---

tools/benchmark/data/maven_top_500.json

It is a bit strange that some specific artifacts are returning out of memory and not the entire package with all versions.

Remove rebuilds with OOM from benchmark

---

tools/ctl/ide/details/details.go

I called it `OSSRebuildVersion` instead of `ExecutorVersion` just to be clearer.

Display oss-rebuild version in metadata

---

pkg/rebuild/maven/infer.go
pkg/rebuild/maven/infer_test.go

If we don't have a URL for particular JDK distribution, we fallback to 11.

Fallback to JDK 11 in case of no URL found

---

internal/api/apiservice/rebuild.go
pkg/rebuild/cratesio/rebuild.go
pkg/rebuild/debian/rebuild.go
pkg/rebuild/maven/rebuild.go
pkg/rebuild/npm/rebuild.go
pkg/rebuild/pypi/rebuild.go
pkg/rebuild/rebuild/rebuild.go

This PR attempts to be be as minimal as possible while still unblocking deprecation of the RebuildRemote interface.

Move timewarp config into Rebuilder interface

---

pkg/rebuild/maven/infer.go
pkg/rebuild/maven/infer_test.go

During inference, we first infer the the path to the pom.xml in the `HEAD` revision. We should ensure that this pom file's basename should exactly be `pom.xml` (and not suffix) and should not be a test resource. This hinder incorrect inference later when we do version heuristic search.
Note, that this only affects 5 artifacts in the current benchmark.

Filter on pom.xml using base name and non test directory

---

tools/ctl/rundex/rundex.go

Does three things:
1. Groups failures due to absent JDK.
2. Groups failures due to cloning repositories.
3. Shortens the error prefix `getting strategy: fetching inference: failed to infer strategy:` to `inference failure:`. This helps with viewing error messages.

Reword errors to group JDK version and shorten them

---

pkg/build/gcb/planner.go

This was originally added in rebuildremote.go but was not ported over
during the refactor.

Copy proxy impl comment from prior build

---

analyzer/network/analyzerservice/analyze.go
internal/api/apiservice/rebuild.go
pkg/rebuild/meta/meta.go
tools/benchmark/run/local.go

It's common that we want to switch using target and get access to the
ecosystem-specific behavior. This package makes that relatively
straightforward, and makes adding new ecosystems easier.

Add meta.AllRebuilders

---

internal/api/agentapiservice/iteration.go
internal/api/apiservice/agent.go

Changing sessionID to be time-sortable for debugging, and change iterationID to have more granularity to avoid collisions

Update sessionID and iterationID formats

---

analyzer/network/analyzerservice/analyze_test.go
internal/verifier/intoto.go
pkg/attestation/bundle.go
pkg/attestation/bundle_test.go

This PR modifies the `InTotoEnvelopeSigner` and tests to correct a bug where the in-toto predicate type URI is being used to populate the DSSE payload type (instead of the [media type as defined in the spec](https://github.com/in-toto/ITE/blob/a6bf0abbc99608ff5920446bf1141417b49a6d30/ITE/5/README.adoc#specification)).
I've also updated the tests to use media type in all the test envelopes.
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@carabiner.dev>

Correct media type in DSSE payload when signing 

---

analyzer/network/analyzerservice/analyze.go
internal/api/agentapiservice/iteration.go
internal/api/apiservice/rebuild.go
internal/api/inferenceservice/infer.go
internal/api/rebuilderservice/smoketest.go
pkg/rebuild/meta/meta.go
tools/benchmark/run/local.go
tools/ctl/ctl.go

During this migration I found a few places where we had RegistryMux
object that were missing an ecosystem. Centralizing it makes it easier
to add new ecosystems in the future.

Add meta.NewRegistryMux

---

pkg/build/gcb/planner.go

We should only throw errors for empty URLs if those assets are actually
going to be generated.

GCB planner only validate necessary asset URLs

---

internal/api/inferenceservice/infer.go

Added the canonicalization in inference service so all ecosystems handled. Now we don't need to add a validator between repo hint and inference. This will throw a general error that canonicalization failed.

Canoncalize repository URL before cloning

---

pkg/rebuild/maven/gradleinfer.go
pkg/rebuild/maven/gradleinfer_test.go

I also changed the log message for Gradle to `no git ref` as in Gradle we don't verify the build.gradle like we do for pom.xml in Maven. In Maven, the artifact ID is looked for in the commit tree. In Gradle, we don't do this. It is merely used for inferring build directory.
I can probably add validation to Gradle too.

Test for gradle inference

---

pkg/rebuild/maven/maveninfer.go
pkg/rebuild/maven/maveninfer_test.go

This won't throw a nil dereferencing error if there is a `fallthrough` from git log heuristic to source jar heuristic and sourceJar guess is `nil`.
I also compute the heuristics lazily. `refMap` is only computed when tag heurisitic does not give a valid match or fails.

Prevent falling through if condition is false

---

deployments/main.tf

This prevents a handful of crashes due to git repo size.

Bump the agent job memory

---

internal/api/agentapiservice/iteration.go

During my testing, this forced timewarp for Maven builds.

Set timewarp based on ecosystem
